#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# mission-control desktop labels
yabai -m space 1 --label dev
yabai -m space 2 --label term
yabai -m space 3 --label web
yabai -m space 4 --label note
yabai -m space 5 --label misc
yabai -m space 6 --label social
yabai -m space 7 --label web2
yabai -m space 8 --label media
yabai -m space 9 --label note
yabai -m space 10 --label note

$HOME/.config/yabai/create_spaces.sh

yabai -m config external_bar               main:35:0     \
                window_border              on           \
                mouse_follows_focus        on          \
                focus_follows_mouse        autoraise          \
                window_placement           second_child \
                window_topmost             on          \
                window_shadow              float        \
                window_opacity             off           \
                window_opacity_duration    0.0         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.95         \
                window_border_width        3            \
                window_border_radius       11           \
                window_animation_duration  0.0         \
                window_border_blur         off            \
                window_border_hidpi        on             \
                active_window_border_color 0xffe1e3e4   \
                normal_window_border_color 0xff2a2f38   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               off          \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                0           \
                bottom_padding             0           \
                left_padding               0           \
                right_padding              0           \
                window_gap                 8


# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)

######## window rules ########

# note
#yabai -m rule --add app="^Obsidian$" space=note

# dev
#yabai -m rule --add app="^Visual Studio Code$" space=dev

# web browser
#yabai -m rule --add app="^Firefox$" space=web

# social
yabai -m rule --add app="^Messages$" space=social
yabai -m rule --add app="^Mail$" space=social
yabai -m rule --add app="^Discord$" space=social

# media
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^iTunes$" space=media
#yabai -m rule --add app="^Firefox Developer Edition$" space=web


# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Vimac|Calculator|Software Update|Dictionary|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$"  sticky=on layer=above manage=off # title="(Co(py|nnect)|Move|Info|Pref)"
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m rule --add app="^licecap$"  sticky=on layer=above manage=off border=off # title="(Co(py|nnect)|Move|Info|Pref)"

yabai -m rule --add label="alt-tab" app="^AltTab" manage=off 
yabai -m rule --add label="karabiner" app="^Karabiner" sticky=on layer=above manage=off border=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
